name: 'Markdown to PDF & Upload Action'
description: 'Generate PDF with ruby gem md-to-pdf and upload to Nextcloud'
author: opf
branding:
  icon: "book"
  color: "purple"

inputs:
  config:
    description: "Config file"
    required: true
    default: "md-to-pdf.config.yml"
  stylings:
    description: "Folder with md-to-pdf stylings"
    required: true
    default: "./stylings"
  nextcloud-user:
    description: "Nextcloud username"
    required: false
  nextcloud-app-access-key:
    description: "Nextcloud app access key"
    required: false
  nextcloud-upload-path:
    description: "Nextcloud host path (e.g. https://nextcloud.example.com/remote.php/dav/files/pdf-bot-user/some-example-path/upload-folder )"
    required: false

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ github.action_path }}

    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache-dependency-path: "${{ github.action_path }}/package-lock.json"

    - run: |
        npm install
        echo "node_modules/.bin" >> "$GITHUB_PATH"
      shell: bash
      working-directory: ${{ github.action_path }}

    - run: |
        bundle exec ruby entrypoint.rb
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        MD2PDF_WORK_DIR: ${{ github.workspace }}
        MD2PDF_CONFIG_FILE: ${{ inputs.config }}
        MD2PDF_STYLING_DIR: ${{ inputs.stylings }}
        NEXTCLOUD_USERNAME: ${{ inputs.nextcloud-user }}
        NEXTCLOUD_APP_ACCESS_KEY: ${{ inputs.nextcloud-app-access-key }}
        NEXTCLOUD_UPLOAD_PATH: ${{ inputs.nextcloud-upload-path }}
